### ISSUE TITLE
Add changelog in about:addons

### ISSUE THREAD

**Issue by beerisgood** [SecUSo/PassSec-plus#10]
Please add a changelog in about:addons (see screenshot)

![addon_changelog](https://cloud.githubusercontent.com/assets/9625159/17225686/42eec5ac-5506-11e6-8903-95741ad220bf.png)

**Comment by krisbr** [comment]
Thanks for the suggestion. I just added the information on the Mozilla website. It should be available in the next few days. In future I'll try to add this information immediately after publishing a new version.

**Comment by beerisgood** [comment]
I doesn't see any update on mozilla or any other site.

**Comment by krisbr** [comment]
As you can see in the picture, I've added those information when I uploaded the new version. Unfortunately I don't know why it's missing there. Do you know if there is another place to put this information?

![passsec](https://cloud.githubusercontent.com/assets/12543756/19835321/c90a0e1a-9e82-11e6-9c3b-648b646ce6e5.PNG)

**Comment by beerisgood** [comment]
Maybe you need to upload a new version. 
Don't know how the mozilla addon site works.

**Comment by krisbr** [comment]
Okay, I'll try that as soon as we release a new version.
