### ISSUE TITLE
Do advertise the download from AMO

### ISSUE THREAD

**Issue by rugk** [SecUSo/PassSec-plus#14]
Follow-up of https://github.com/SecUSo/PassSec-plus/issues/6

I think you should not advertise the download from [your own website](https://www.secuso.informatik.tu-darmstadt.de/?id=10387) unless the add-on has an automatic updater (which does not seem to be the case here), because this means users may stick with outdated versions of the add-on without knowing it.

**Comment by krisbr** [comment]
Thanks for filing this issue. I thought that if we would distribute the same file of the add-on which is distributed on the website, users would be updated automatically.
I removed the download link, now they lead to the Mozilla store.

**Comment by rugk** [comment]
> I thought that if we would distribute the same file of the add-on which is distributed on the website, users would be updated automatically.

Mhh, I don't know whether it works this way, but you could be right.
Anyway a link to the AMO store might be better as users usually download add-ons there and should be trained to not install too much stuff from third-parties.

As you fixed the problem I can close this issue.
