### ISSUE TITLE
TypeError: can't access dead object

### ISSUE THREAD

**Issue by beerisgood** [SecUSo/PassSec-plus#16]
In Pale Moon 27 (beta 3) i get that error (a lot and ~every second) in error console:
Error: TypeError: can't access dead object

Source File: chrome://firefoxpasswordwarningextension/content/jquery-3.1.0.min.js
Line: 2

**Comment by krisbr** [comment]
Thanks for the bug report. We will try to fix this bug in the next release.

**Comment by beerisgood** [comment]
Nice to hear that!

**Comment by beerisgood** [comment]
*push*
