### ISSUE TITLE
Adding exceptions for IP adresses does not work

### ISSUE THREAD

**Issue by McNetic** [SecUSo/PassSec-plus#3]
When I try to add an exception on a site loaded via IP adress, the initial warning dialog reappears instead of the confirmation dialog. It is thus not possible to add an exception for the ip address.

This would be especially useful for web developers (as in my case), to whitelist the development machines and/or the localhost.

**Comment by krisbr** [comment]
Thanks for the suggestion and sorry for the late reply. I just added the support of IP adresses.

**Comment by McNetic** [comment]
Thank you very much.
