### ISSUE TITLE
High CPU usage if combined with KeeFox

### ISSUE THREAD

**Issue by maxanier** [SecUSo/PassSec-plus#5]
Firefox uses quite a large CPU workload since I've installed PassSec. Even if only the "new tab" tab is open Firefox uses up to 30% of my CPU (On an i5 2500k).
After some testing it seems that PassSec isn't working very well if used together with KeeFox.
If both addons are activated at the same time Firefox is using a lot of CPU time, if only one is activated everything is fine (around 1-3%).

There was a issue on the KeeFox repository, but I did not seem as there was any result. But maybe someone of that discussion has already informed you about this:
https://github.com/luckyrat/KeeFox/issues/539 (At the end).

Hope this can be sorted out, since I would really like to use both addons, thanks :)

Firefox (64 bit) 44.0.2
PassSec+ 1.1.6
KeeFox 1.5.4
Windows 10

**Comment by krisbr** [comment]
Thanks for your bug report. I just released a new version (1.2.0) of PassSec+ today, could you please test it and tell me if it resolves the problem with the high CPU usage? 
A few beta testers also had these problems and they told me that the version resolved them. It's probably related to the JQuery library which is used by both add-ons. I've updated the library in this release, so hopefully it solves the problem for your as well.

**Comment by maxanier** [comment]
The new version seems to fix it. Thanks :)
